### PR TITLE
Added new features, defaults fixed

### PR DESCRIPTION
**Pull request by kovapatrik**
Hi again!

I added more customizable options and fixed default.

The defaults didn't worked with your code, because the object itself was set to a default value.
Instead of that, I seperated all the variables.

In Svelte, you can pass easily an object with the spread operator to a component like this:

```
let toggleCSS = {
    fontSize: '1.2em',
    align: 'left',
    borderTop: 'none', 
    paddingTop: 0, 
    paddingBottom: '0.1em',
    marginTop: 0
  }

<Toggle {...toggleCSS} />
```

and the variables in the component will got the corresponding values.

Secondly, I added more options, like paddings, margins and borders.

### CODE REVIEW

**Comment by antony** [comment]
Looks good! I'll review as soon as I have a minute.

**Comment by kovapatrik** [comment]
Have you made any progress? I would like to use the master branch for my project to be up to date if any changes made in the future.

**Comment by antony** [comment]
Sorry, slipped my mind. I'll review tonight / tomorrow and cut a release!

Apologies for the delay.

**Review by antony — APPROVED** [review]

**Comment by antony** [comment]
Released as 1.2.0 - thanks!

**Pull request merged**
